import cohere
import os
from cohere.responses.classify import Example

co = cohere.Client(os.environ.get('COHERE_API_KEY'))

examples1 = [
    Example("I am sad", "happyspec"),
    Example("I am happy", "happy"),
    Example("I am angry", "angry"),
    Example("I am unhappy", "happyspec"),
    Example("I am excited", "happy"),
    Example("I am upset", "angry"),
    Example("cheer me up", "happyspec"),
    Example("I'm feeling good", "happy"),
    Example("I'm not happy", "angry"),
    Example("It's been rough", "happyspec"),
    Example("I've been good", "happy"),
    Example("I am bothered", "angry"),
    Example("Show me a sad photo", "sad"),
    Example("Show me a happy photo", "happy"),
    Example("Show me a angry photo", "angry"),
    Example("Remind me of a sad moment", "sad"),
    Example("Remind me of a happy moment", "happy"),
    Example("Remind me of a moment where I was angry", "angry"),
    Example("When was I sad?", "sad"),
    Example("When was I happy?", "happy"),
    Example("When was I angry?", "angry"),
    Example("Throwback to a depressing time", "sad"),
    Example("Throwback to a joyous time", "happy"),
    Example("Throwback to an annoying time", "angry"),
    Example("I am scared", "fear"),
    Example("I am neutral", "neutral"),
    Example("I am surprised", "surprise"),
    Example("I am fearful", "fear"),
    Example("I am okay", "neutral"),
    Example("That was unexpected", "surprise"),
    Example("Terrify me", "fear"),
    Example("I am beyond pissed", "happyspec"),
    Example("I'm feeling fine", "neutral"),
    Example("I was not anticipating that", "surprise"),
    Example("That was scary", "fear"),
    Example("I've been doing alright", "neutral"),
    Example("My heart is racing", "surprise"),
    Example("Show me a horror photo", "fear"),
    Example("Show me a neutral photo", "neutral"),
    Example("Show me a surprising photo", "surprise"),
    Example("Remind me of a scary moment", "fear"),
    Example("Remind me of a neutral moment", "neutral"),
    Example("Remind me of a moment where I was surprised", "surprise"),
    Example("When was I afraid?", "fear"),
    Example("When was I neutral?", "neutral"),
    Example("When was I surprised?", "surprise"),
    Example("Throwback to a horrifying time", "fear"),
    Example("Throwback to a mediocre time", "neutral"),
    Example("Throwback to an out of the ordinary time", "surprise"),
    Example("I'm feeling blue", "happyspec"),
    Example("I'm over the moon", "happy"),
    Example("I'm seeing red", "happyspec"),
    Example("I'm down in the dumps", "happyspec"),
    Example("I'm on cloud nine", "happy"),
    Example("I'm steamed", "angry"),
    Example("Can you lift my spirits?", "happyspec"),
    Example("I'm in high spirits", "happy"),
    Example("I'm at the end of my rope", "happyspec"),
    Example("It's been a tough day", "happyspec"),
    Example("I'm on top of the world", "happy"),
    Example("I'm fuming", "happyspec"),
    Example("Give me a reason to smile", "happyspec"),
    Example("I'm feeling fantastic", "happy"),
    Example("I'm seething with anger", "happyspec"),
    Example("It's been a rough patch", "happyspec"),
    Example("I'm having a blast", "happy"),
    Example("I'm about to blow a gasket", "happyspec"),
    Example("I'm feeling glum", "happyspec"),
    Example("Life is good", "happy"),
    Example("I'm seeing black", "happyspec"),
    Example("Show me a sad photo", "sad"),
    Example("Show me a happy photo", "happy"),
    Example("Show me an angry photo", "angry"),
    Example("Display a photo that makes me smile", "happy"),
    Example("Can you find a picture that captures joy?", "happy"),
    Example("I want to see a photo that reflects anger", "angry"),
    Example("Show me a photo that evokes sadness", "sad"),
    Example("Can you find an image that represents happiness?", "happy"),
    Example("I'm in the mood for a picture that conveys anger", "angry"),
    Example("Display a photo that brings tears to my eyes", "sad"),
    Example("Can you find a picture that makes me laugh?", "happy"),
    Example("Show me an image that shows frustration", "angry"),
    Example("I want to see a photo that depicts melancholy", "sad"),
    Example("Display a photo that radiates positivity", "happy"),
    Example("Can you find an image that illustrates sorrow?", "sad"),
    Example("Show me a picture that reflects excitement", "happy"),
    Example("I'm curious to see a photo that embodies rage", "angry"),
    Example("Can you find an image that shows disappointment?", "sad"),
    Example("Show me a photo that represents contentment", "happy"),
    Example("Show me a photo of when I was in a dark place", "sad"),
]

examples2 = [
    Example("Show me a selfie", "individual"),
    Example("Show me a group photo", "group"),
    Example("Show me a happy photo of myself", "individual"),
    Example("Show me a good moment with friends", "group"),
    Example("A photo of me", "individual"),
    Example("A photo with my family", "group"),
    Example("Show me a time when I was sad", "individual"),
    Example("Show me a time where my friends and I were unhappy", "group"),
    Example("A time when I was alone", "individual"),
    Example("A time when I was with others", "group"),
    Example("When was I by myself?", "individual"),
    Example("When was I with people?", "group"),
    Example("A lonely photo", "individual"),
    Example("An unforgettable moment with friends", "group"),
    Example("Me independent", "individual"),
    Example("A class of students", "group"),
    Example("I'd like to see a solo picture", "individual"),
    Example("I want to view a photo of just me", "individual"),
    Example("Can you show me an image of myself alone?", "individual"),
    Example("Display a photograph of me without others", "individual"),
    Example("I'm interested in seeing a selfie", "individual"),
    Example("I'm looking for a picture where I'm the only one", "individual"),
    Example("Show me a photo of myself", "individual"),
    Example("I want to see a picture of just me", "individual"),
    Example("I'm curious to see a photograph of myself", "individual"),
    Example("Can you find a photo of me by myself?", "individual"),
    Example("Display a group photo", "group"),
    Example("I want to view a picture with others", "group"),
    Example("Show me a photo with my friends", "group"),
    Example("I'm interested in seeing a group photograph", "group"),
    Example("Can you find a picture of me and my family?", "group"),
    Example("Display a photo with a bunch of people", "group"),
    Example("I want to see a picture with a group of people", "group"),
    Example("Show me a photograph of a crowd", "group"),
    Example("I'd like to view a photo of my classmates", "group"),
    Example("I'm interested in seeing a group shot", "group"),
]

def intent(text_input):
    inputs = [text_input]
    response1 = co.classify(
        inputs=inputs,
        examples=examples1,
    )
    if float(response1[0].confidences[0]) < 0.8:
        mood = "nonsense"
    else:
        mood = response1[0].predictions[0]

    response2 = co.classify(
        inputs=inputs,
        examples=examples2,
    )
    setting = response2[0].predictions[0]

    if mood == "happyspec":
        result = "happy group"
    else:
        result = mood + " " + setting
    return result